#!/usr/bin/ruby

if ARGV[0].nil?
   puts "usage: publish [local] filename"
   exit(-2)
end

if ARGV[0] == "remote"
   if !ARGV[1].nil?
      src_file = ARGV[1]
      dest_location = "home:www/public/notes"
   else
      puts "usage: publish [local] filename"
      exit(-2)
   end
else
   src_file = ARGV[0]
   dest_location = "~/docs/notes/published"
end

# Could try to use markdown gem later

# Shell method
dest_file = src_file.sub(/\.md/, ".html")

`markdown < #{src_file} > #{dest_file}`

# Transfer (Reads from stdin, less cleanup)
puts `rsync #{dest_file} #{dest_location}`

# Clean up
`rm #{dest_file}`
